
public class ALGEBRA_CATEGORIES {
	
	public int ALGEBRA_CATEGORY_INTEGER_OPERANDS;
	public int ALGEBRA_CATEGORY_INTEGER_ANSWERS;
	public int ALGEBRA_CATEGORY_FRACTIONS_OPERANDS;
	public int ALGEBRA_CATEGORY_FRACTIONS_ANSWERS;
	public int ALGEBRA_CATEGORY_DOUBLE_OPERANDS;
	public int ALGEBRA_CATEGORY_DOUBLE_ANSWERS;
	
	

}
